eval "$(/opt/homebrew/bin/brew shellenv)"
export ZSH="$HOME/.oh-my-zsh"
plugins=(git docker kubectl)
source $ZSH/oh-my-zsh.sh
source $HOME/dotfiles/zsh/aliases.zsh
eval "$(starship init zsh)"
export PATH="$HOME/.local/bin:$HOME/dotfiles/pyscripts:$PATH"
